name: mpclounge
favicon: null
layout_spectrum: 0.8839898738078773
typography_spectrum: 0.4956687674857676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11026446218602359
  lightness: 0.12435012101195753
  saturation: 0.9503494692035019
  rhythmicContrast: 0.8068413003347814
purpose: []
